config/routes.rb
Spotted::Application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register'
  }

  root to: 'home#index'

  get 'contact',  controller: :home, action: :contact,  as: :contact
  get 'infos',    controller: :home, action: :infos,    as: :infos

  resources :users
  resource :user, path: :account, as: :account

  namespace :admin do
    root 'users#index'

    resources :users
    resources :spots do
      resources :shoots do
        resources :photos
      end
    end
    resources :schools
    resources :orders
  end

  resources :spots do
    collection do
      get :markers
    end
    resources :shoots do
      resources :photos
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    @user = user

    load @user.admin? ? :admin : :default
  end

  def load *permissions
    permissions.map {|perm| perm.to_s.gsub '::', '_' }.each {|perm| self.send perm if self.respond_to? perm }
  end

  def default
    can :manage, User, id: @user.id
  end

  def admin
    can :access, :admin
    can :manage, :all
  end
end

app/models/line.rb
class Line < ActiveRecord::Base
  belongs_to :order
  belongs_to :photo

  validates :order, presence: true
  validates :photo, presence: true
  validates :quantity, presence: true
end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :payments
  has_many :lines
  has_many :photos, through: :lines

  validates :user, presence: true

  def paid?
    payments.where('payed_at is not null').empty? ? false : true
  end

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :order

  validates :order, presence: true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :shoot

  mount_uploader :file, FileUploader

  validates :shoot, presence: true
  validates :file, presence: true

end

app/models/school.rb
class School < ActiveRecord::Base
  has_many :shoots
  has_many :photos, through: :shoots
  has_many :orders

  validates :name, presence: true, uniqueness: true
  validates :coupon, uniqueness: true
end

app/models/shoot.rb
class Shoot < ActiveRecord::Base
  belongs_to :spot
  has_many :photos

  validates :spot, presence: true
  validates :shooted_at, presence: true

end

app/models/spot.rb
class Spot < ActiveRecord::Base
  has_many :shoots
  has_many :photos, through: :shoots

  validates :name, presence: true, uniqueness: { scope: :country }
  validates :country, presence: true

  geocoded_by :address, latitude: :lat, longitude: :lng

  before_save :geocode

  def geocode!
    geocode
    save
  end

  def address
    [name, country].join(', ')
  end

  def as_json options={}
    {name: name, lat: lat, lng: lng, id: id}
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :orders
  has_many :payments, through: :orders
  has_many :lines, through: :orders
  has_many :photos, through: :lines

  validates :first_name, presence: true

  def name
    [first_name, last_name].join(' ')
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :admin_restricted

  def admin_restricted
    unless can? :access, :admin
      redirect_to root_path
    end
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController
end

app/controllers/admin/photos_controller.rb
class Admin::PhotosController < Admin::BaseController
  before_filter :load_spot
  before_filter :load_shoot

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new photo_params
    @photo.shoot = @shoot
    if @photo.save
      redirect_to [:new, :admin, @spot, @shoot, :photo]
    else
      render action: 'new'
    end
  end

  private

  def load_spot
    @spot = Spot.find params[:spot_id]
  end

  def load_shoot
    @shoot = Shoot.find params[:shoot_id]
  end

  def photo_params
    params.require(:photo).permit(:file)
  end

end

app/controllers/admin/schools_controller.rb
class Admin::SchoolsController < Admin::BaseController
end

app/controllers/admin/shoots_controller.rb
class Admin::ShootsController < Admin::BaseController
  before_filter :fetch_spot
  before_filter :fetch_shoot, only: [:show, :edit, :update, :delete]

  layout 'application'

  def index
    @shoots = Shoot.all
  end

  def new
    @shoot = Shoot.new
  end

  def create
    @shoot = Shoot.new shoot_params
    @shoot.spot = @spot
    if @shoot.save
      redirect_to [:admin, @spot, @shoot]
    else
      render action: 'new'
    end
  end

  private

  def fetch_spot
    @spot = Spot.find params[:spot_id]
  end

  def fetch_shoot
    @shoot = Shoot.find params[:id]
  end

  def shoot_params
    params.require(:shoot).permit(:shooted_at)
  end
end

app/controllers/admin/spots_controller.rb
class Admin::SpotsController < Admin::BaseController
  before_filter :fetch_spot, only: [:show, :edit, :update, :delete]

  layout 'application'

  def index
    @spots = Spot.all
  end

  def new
    @spot = Spot.new
  end

  def create
    @spot = Spot.new spot_params
    if @spot.save
      redirect_to [:admin, @spot]
    else
      render action: 'new'
    end
  end

  private

  def fetch_spot
    @spot = Spot.find params[:id]
  end

  def spot_params
    params.require(:spot).permit(:name, :country)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_filter :fetch_user, only: [:show, :edit, :update, :delete]

  layout 'application'

  def index
    @users = User.all
  end

  def update
    if @user.update_attributes user_params
      redirect_to [:admin, @user]
    else
      render action: 'edit'
    end
  end

  private

  def fetch_user
    @user = User.find params[:id]
  end

  def user_params
    params[:user].delete_if { |k, v| v.empty? }
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :admin)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation) }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def contact
    @message = Message.new
  end

  def infos
  end
end

app/controllers/shoots_controller.rb
class ShootsController < ApplicationController
  before_filter :fetch_spot
  before_filter :fetch_shoot, only: :show

  def show
  end

  private

  def fetch_spot
    @spot = Spot.find params[:spot_id]
  end

  def fetch_shoot
    @shoot = Shoot.find params[:id]
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_filter :fetch_spot, only: :show

  respond_to :html, except: :markers
  respond_to :json, only: :markers

  def index
    @spots = Spot.all
  end

  def markers
    respond_with Spot.all.to_json
  end

  private

  def fetch_spot
    @spot = Spot.find params[:id]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  before_filter :authenticate_user!, only: [:show, :edit, :update]
  before_filter :fetch_user, only: [:show, :edit, :update]

  def show
  end

  private

  def fetch_user
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shoots/_form.html.haml
.form-group
  = f.label :shooted_at, class: 'col-sm-2 control-label'
  .col-sm-10
    = f.date_field :shooted_at, class: 'form-control', placeholder: 'Shooted at'

app/views/admin/shoots/new.html.haml
.container
  %ol.breadcrumb
    %li= link_to 'Spots', [:admin, :spots]
    %li= link_to @spot.name, [:admin, @spot]
    %li.active= 'New shoot'

  = form_for @shoot, url: [:admin, @spot, :shoots], html: { class: 'form-horizontal' } do |f|
    = render partial: 'form', locals: { f: f }
    .form-group
      .col-sm-offset-2.col-sm-10
        = link_to 'Cancel', [:admin, @spot], class: 'btn btn-default'
        = f.submit 'Save', class: 'btn btn-primary'

app/views/admin/shoots/show.html.haml
.container
  %ol.breadcrumb
    %li= link_to 'Spots', [:admin, :spots]
    %li= link_to @spot.name, [:admin, @spot]
    %li= link_to 'Shoots', [:admin, @spot]
    %li.active= @shoot.shooted_at
    .pull-right
      = link_to 'Add photos', [:new, :admin, @spot, @shoot, :photo]

  .row
    - @shoot.photos.each do |photo|
      .col-lg-2
        .shoot.shoot_admin
          .content
            = image_tag photo.file.small.url

app/views/admin/spots/_form.html.haml
.form-group
  = f.label :name, class: 'col-sm-2 control-label'
  .col-sm-10
    = f.text_field :name, class: 'form-control', placeholder: 'Name'
.form-group
  = f.label :country, class: 'col-sm-2 control-label'
  .col-sm-10
    = f.text_field :country, class: 'form-control', placeholder: 'Country'

app/views/admin/spots/index.html.haml
.container
  %ol.breadcrumb
    %li.active Spots
    .pull-right
      = link_to 'New spot', new_admin_spot_path

  %table.table
    %thead
      %tr
        %th Name
        %th Country
        %th Total of shoots
        %th Total of photos
        %th
    %tbody
      - @spots.each do |spot|
        %tr
          %td= link_to spot.name, [:admin, spot]
          %td= spot.country
          %td= spot.shoots.count
          %td= spot.photos.count
          %td

app/views/admin/spots/new.html.haml
.container
  %ol.breadcrumb
    %li= link_to 'Spots', [:admin, :spots]
    %li.active New spot

  = form_for @spot, url: [:admin, :spots], html: { class: 'form-horizontal' } do |f|
    = render partial: 'form', locals: { f: f }
    .form-group
      .col-sm-offset-2.col-sm-10
        = link_to 'Cancel', [:admin, :spots], class: 'btn btn-default'
        = f.submit 'Save', class: 'btn btn-primary'

app/views/admin/spots/show.html.haml
.container
  %ol.breadcrumb
    %li= link_to 'Spots', [:admin, :spots]
    %li.active= "#{@spot.name} (#{@spot.country})"
    .pull-right
      = link_to 'New shoot', [:new, :admin, @spot, :shoot]

  %table.table
    %thead
      %tr
        %th Session date
        %th Number of photos
        %th
    %tbody
      - @spot.shoots.each do |shoot|
        %tr
          %td= link_to shoot.shooted_at, [:admin, @spot, shoot]
          %td= shoot.photos.count
          %td

app/views/admin/users/edit.html.haml
.container
  %ol.breadcrumb
    %li= link_to 'Users', [:admin, :users]
    %li.active= @user.name

  = form_for @user, url: [:admin, @user], html: { class: 'form-horizontal' } do |f|
    .row
      .col-lg-6
        %h3 Account informations
        %hr
        .form-group
          = f.label :first_name, class: 'col-sm-3 control-label input-required'
          .col-sm-9
            = f.text_field :first_name, class: 'form-control', placeholder: 'First name'
        .form-group
          = f.label :last_name, class: 'col-sm-3 control-label'
          .col-sm-9
            = f.text_field :last_name, class: 'form-control', placeholder: 'Last name'
        .form-group
          = f.label :email, class: 'col-sm-3 control-label input-required'
          .col-sm-9
            = f.text_field :email, class: 'form-control', placeholder: 'Email'
      .col-lg-6
        %h3 Authentification informations
        %hr
        .form-group
          = f.label :password, class: 'col-sm-3 control-label input-required'
          .col-sm-9
            = f.password_field :password, class: 'form-control', placeholder: 'Password'
        .form-group
          = f.label :confirmation, class: 'col-sm-3 control-label input-required'
          .col-sm-9
            = f.password_field :password_confirmation, class: 'form-control', placeholder: 'Password confirmation'
    .row
      .col-lg-6
        %h3 Permissions
        %hr
        .form-group
          = f.label :admin, class: 'col-sm-3 control-label'
          .col-sm-9.checkbox
            = f.check_box :admin
    .row
      .col-lg-6
        .form-group
          .col-lg-offset-3.col-lg-9
            = link_to 'Cancel', [:admin, @user], class: 'btn btn-default'
            = f.submit 'Save', class: 'btn btn-primary'

app/views/admin/users/index.html.haml
.container
  %ol.breadcrumb
    %li.active Users

  %table.table.table-striped
    %thead
      %tr
        %th Name
        %th eMail
        %th.col-sm-1
    %tbody
      - @users.each do |user|
        %tr
          %td= link_to user.name, [:admin, user]
          %td= mail_to user.email
          %td
            = link_to [:edit, :admin, user] do
              %i.icon-pencil-1
            %i.icon-cancel-alt-filled

app/views/admin/users/show.html.haml
.container
  %ol.breadcrumb
    %li= link_to 'Users', [:admin, :users]
    %li.active= @user.name
    .pull-right
      = link_to 'Edit', [:edit, :admin, @user]

  .row
    - if @user.confirmed_at.nil?
      .col-lg-12
        .alert.alert-danger Unconfirmed user
    .col-lg-6
      %h3 Account informations
      %hr
      .row
        .col-sm-3.label Name
        .col-sm-9= @user.name
      .row
        .col-sm-3.label Email
        .col-sm-9= @user.email
    .col-lg-6
      %h3 Orders
      %hr

app/views/shoots/show.html.haml
.container
  %h1= "Shoot at #{@spot.name} (#{@spot.country}) the #{@shoot.shooted_at}"
  %h3= "#{@shoot.photos.count} photos"
  .row
    - @shoot.photos.each do |photo|
      .col-sm-3
        .shoot
          .content
            = image_tag photo.file.small.url
          .overlay{style: 'display: none'}
            = link_to '#' do
              %i.icon-resize-full-circle
            = link_to '#' do
              %i.icon-basket
            = link_to '#', class: 'share fb-share', data: { url: request.protocol + request.host_with_port + photo.file.big.url } do
              %i.icon-facebook-squared

app/views/spots/index.html.haml
.container
  %h1 Choose your spot
#map_canvas.map{data: {source: url_for([:markers, :spots])}}

app/views/spots/show.html.haml
.container
  %h2= "Shoot at #{@spot.name}"
  #shoot_at_spot.row
    - @spot.shoots.each do |shoot|
      .col-lg-4
        .shoot
          = link_to [shoot.spot, shoot] do
            .content
              = image_tag shoot.photos.first.file.medium.url
              %infos
                %h3= shoot.spot.name
                %i= shoot.shooted_at
                .more= "#{shoot.photos.count} Shoots"

app/views/users/_form_new.html.haml
.form-group
  = f.label :first_name, class: 'col-sm-3 control-label input-required'
  .col-sm-9
    = f.text_field :first_name, class: 'form-control', placeholder: 'First name'
.form-group
  = f.label :last_name, class: 'col-sm-3 control-label'
  .col-sm-9
    = f.text_field :last_name, class: 'form-control', placeholder: 'Last name'
.form-group
  = f.label :email, class: 'col-sm-3 control-label input-required'
  .col-sm-9
    = f.text_field :email, class: 'form-control', placeholder: 'Email'
.form-group
  = f.label :password, class: 'col-sm-3 control-label input-required'
  .col-sm-9
    = f.password_field :password, class: 'form-control', placeholder: 'Password'
.form-group
  = f.label :confirmation, class: 'col-sm-3 control-label input-required'
  .col-sm-9
    = f.password_field :password_confirmation, class: 'form-control', placeholder: 'Password confirmation'

app/views/users/new.html.haml
.container
  %h2 Register
  .row
    .col-lg-6
      = form_for @user, url: [:users], html: { class: 'form-horizontal' } do |f|
        = render partial: 'form_new', locals: { f: f }
        .form-group
          .col-sm-offset-3.col-sm-9
            = f.submit 'Register', class: 'btn btn-primary'

app/views/users/show.html.haml
.container
  %h2 My account
  .row
    .col-lg-6
      %h3 Account informations
      %hr
      .row
        .col-sm-3.label Name
        .col-sm-9= @user.name
      .row
        .col-sm-3.label Email
        .col-sm-9= @user.email
      .row
        .col-sm-3.label Password
        .col-sm-9 **********
      .row
        .col-sm-offset-3.col-sm-9
          = link_to 'Edit', edit_account_path, class: 'btn btn-primary'
    .col-lg-6
      %h3 Previous orders
      %hr
      %table.table
        %tbody
          - @user.orders.order('created_at desc').each do |order|
            %tr
              %td= order.created_at
              %td= order.payed_at