config/routes.rb
Spotted::Application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register'
  }

  root to: 'home#index'

  get 'contact',  controller: :home, action: :contact,  as: :contact
  get 'infos',    controller: :home, action: :infos,    as: :infos

  resources :users
  resource :user, path: :account, as: :account

  namespace :admin do
    root 'users#index'

    resources :users
    resources :spots do
      resources :shoots do
        resources :photos
      end
    end
    resources :schools
    resources :orders
  end

  resources :spots do
    collection do
      get :markers
    end
    resources :shoots do
      resources :photos
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    @user = user

    load @user.admin? ? :admin : :default
  end

  def load *permissions
    permissions.map {|perm| perm.to_s.gsub '::', '_' }.each {|perm| self.send perm if self.respond_to? perm }
  end

  def default
    can :manage, User, id: @user.id
  end

  def admin
    can :access, :admin
    can :manage, :all
  end
end

app/models/line.rb
class Line < ActiveRecord::Base
  belongs_to :order
  belongs_to :photo

  validates :order, presence: true
  validates :photo, presence: true
  validates :quantity, presence: true
end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :payments
  has_many :lines
  has_many :photos, through: :lines

  validates :user, presence: true

  def paid?
    payments.where('payed_at is not null').empty? ? false : true
  end

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :order

  validates :order, presence: true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :shoot

  mount_uploader :file, FileUploader

  validates :shoot, presence: true
  validates :file, presence: true

end

app/models/school.rb
class School < ActiveRecord::Base
  has_many :shoots
  has_many :photos, through: :shoots
  has_many :orders

  validates :name, presence: true, uniqueness: true
  validates :coupon, uniqueness: true
end

app/models/shoot.rb
class Shoot < ActiveRecord::Base
  belongs_to :spot
  has_many :photos

  validates :spot, presence: true
  validates :shooted_at, presence: true

end

app/models/spot.rb
class Spot < ActiveRecord::Base
  has_many :shoots
  has_many :photos, through: :shoots

  validates :name, presence: true, uniqueness: { scope: :country }
  validates :country, presence: true

  geocoded_by :address, latitude: :lat, longitude: :lng

  before_save :geocode

  def geocode!
    geocode
    save
  end

  def address
    [name, country].join(', ')
  end

  def as_json options={}
    {name: name, lat: lat, lng: lng, id: id}
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :orders
  has_many :payments, through: :orders
  has_many :lines, through: :orders
  has_many :photos, through: :lines

  validates :first_name, presence: true

  def name
    [first_name, last_name].join(' ')
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :admin_restricted

  def admin_restricted
    unless can? :access, :admin
      redirect_to root_path
    end
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController
end

app/controllers/admin/spots_controller.rb
class Admin::SpotsController < Admin::BaseController
  before_filter :fetch_spot, only: [:show, :edit, :update, :delete]

  layout 'application'

  def index
    @spots = Spot.all
  end

  def new
    @spot = Spot.new
  end

  def create
    @spot = Spot.new spot_params
    if @spot.save
      redirect_to [:admin, @spot]
    else
      render action: 'new'
    end
  end

  private

  def fetch_spot
    @spot = Spot.find params[:id]
  end

  def spot_params
    params.require(:spot).permit(:name, :country)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_filter :fetch_user, only: [:show, :edit, :update, :delete]

  layout 'application'

  def index
    @users = User.all
  end

  def update
    if @user.update_attributes user_params
      redirect_to [:admin, @user]
    else
      render action: 'edit'
    end
  end

  private

  def fetch_user
    @user = User.find params[:id]
  end

  def user_params
    params[:user].delete_if { |k, v| v.empty? }
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :admin)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation) }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def contact
    @message = Message.new
  end

  def infos
  end
end

app/controllers/shoots_controller.rb
class ShootsController < ApplicationController
  before_filter :fetch_spot
  before_filter :fetch_shoot, only: :show

  def show
  end

  private

  def fetch_spot
    @spot = Spot.find params[:spot_id]
  end

  def fetch_shoot
    @shoot = Shoot.find params[:id]
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_filter :fetch_spot, only: :show

  respond_to :html, except: :markers
  respond_to :json, only: :markers

  def index
    @spots = Spot.all
  end

  def markers
    respond_with Spot.all.to_json
  end

  private

  def fetch_spot
    @spot = Spot.find params[:id]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  before_filter :authenticate_user!, only: [:show, :edit, :update]
  before_filter :fetch_user, only: [:show, :edit, :update]

  def show
  end

  private

  def fetch_user
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{name: "viewport", content: "initial-scale = 1.0, maximum-scale = 1.0, user-scalable = no, width = device-width"}
    %title Spotted
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %header
      %nav.navbar.navbar-fixed-top
        .container
          = link_to 'Spotted', root_path, class: 'navbar-brand'
          .collapse.navbar-collapse
            %ul.nav.navbar-nav.pull-right
              = render partial: controller.class.name.split('::').first == 'Admin' ? 'shared/menu_admin' : 'shared/menu_public'
      = yield :header

    %content
      = yield

    %footer
      .container
        .row
          .col-lg-4
            %h2 Spotted
            Developped by uberPixel Ltd
          .col-lg-4.social
            = link_to 'https://www.facebook.com/spotted.mu' do
              %i.icon-facebook-squared
            %i.icon-twitter
            %i.icon-gplus
            %i.icon-instagram
            = mail_to 'hello@spotted.mu' do
              %i.icon-mail
          .col-lg-4
            %ul
              %li
                = link_to root_path do
                  Home
                  %i.icon-home
              %li
                = link_to spots_path do
                  Spots
                  %i.icon-globe
              %li
                = link_to '#' do
                  Blog
                  %i.icon-book-open
              %li
                = link_to [:contact] do
                  Contact
                  %i.icon-direction-outline
              %li
                = link_to '#' do
                  Login
                  %i.icon-lock-filled

    %script{src: "https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"}
    = javascript_include_tag "application", "data-turbolinks-track" => true

app/views/shared/_menu_admin.html.haml
%li{class: controller_name.include?('users') ? 'active' : '' }
  = link_to 'Users', [:admin, :users]
%li{class: ['spots', 'shoots'].include?(controller_name) ? 'active' : ''}
  = link_to 'Spots', [:admin, :spots]
%li
  = link_to 'Orders', [:admin, :orders]
%li
  = link_to 'Schools', [:admin, :schools]

app/views/shared/_menu_public.html.haml
%li{class: controller_name.include?('home') && action_name.include?('index') ? 'active' : ''}
  = link_to 'Home', root_path
%li{class: ['spots', 'shoots'].include?(controller_name) ? 'active' : ''}
  = link_to 'Spots', spots_path
%li
  = link_to 'Blog', '#'
%li{class: controller_name.include?('home') && action_name.include?('contact') ? 'active' : ''}
  = link_to 'Contact', [:contact]
%li{class: ['sessions', 'users'].include?(controller_name) ? 'active' : ''}
  - if current_user
    = link_to 'My account', account_path
  - else
    = link_to 'Login', new_user_session_path